server:
    port: 8080
file:
    upload:
        path: ./files
http:
    api:
        url: http://127.0.0.1:8010/
spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB
    datasource:
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        url: "jdbc:p6spy:mysql://localhost:3306/hajime?useSSL=false"
        username: myuser
        password: mypassword
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            initialSize: 5
            minIdle: 5
            maxActive: 50
            maxWait: 60000
            validationQuery: SELECT 1 FROM DUAL
    web:
        resources:
            static-locations: file:./files/
sa-token:
    token-name: Authorization
    # Token expiration date (unit: seconds) The default is 30 days, and -1 means it is valid forever
    timeout: 86400
    # Enable authentication for private network service calls
    check-same-token: true
    active-timeout: 1800
    is-concurrent: true
    is-share: true
    # token style uuid、simple-uuid、random-32、random-64、random-128、tik
    token-style: uuid
    # token prefix
    token-prefix: ""
    jwt-secret-key: abcdegfghijklxcmnopqdenrstuvwxyz
    is-log: true
swagger:
    enabled: true
    title: Hajime Admin API Doc
    description: desc interface test
    version: 1.0.0
    contact:
        name: xc.deng
        url:
        email:
    package: ai.hajimebot.controller
secure:
    ignored:
        urls:
            - /
            - /swagger-ui/**
            - /swagger-resources/**
            - /v3/**
            - /user/login
            - /user/doLogin
            - /user/doLoginByWallet
            - /user/isLogin